project_id = "bzyvykyuiuihzvhdpxsi"

[functions.send-whatsapp-badge]
verify_jwt = false

[functions.send-vehicle-whatsapp]
verify_jwt = false

[functions.notify-host]
verify_jwt = false

[functions.send-email-badge]
verify_jwt = false

[functions.approve-visitor]
verify_jwt = false

[functions.send-sms-badge]
verify_jwt = false
